// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUNIUsgk1yNvBAUEwAbWg87XDOBLHffAQ',
    appId: '1:217237713046:web:f6a476d52e0ac8462912b7',
    messagingSenderId: '217237713046',
    projectId: 'vi-assistant',
    authDomain: 'vi-assistant.firebaseapp.com',
    storageBucket: 'vi-assistant.firebasestorage.app',
    measurementId: 'G-ESJS4CL4GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVQfZh6yott-Zx2oF64V0jQxqgHwW_iRc',
    appId: '1:217237713046:android:6cf3d20504c27ee02912b7',
    messagingSenderId: '217237713046',
    projectId: 'vi-assistant',
    storageBucket: 'vi-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gznmUqJlgIjkxBpHPfnRMz3-Z2UKhvE',
    appId: '1:217237713046:ios:e8bc31c48cd396482912b7',
    messagingSenderId: '217237713046',
    projectId: 'vi-assistant',
    storageBucket: 'vi-assistant.firebasestorage.app',
    iosBundleId: 'com.example.viAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUNIUsgk1yNvBAUEwAbWg87XDOBLHffAQ',
    appId: '1:217237713046:web:05717452fec7a9152912b7',
    messagingSenderId: '217237713046',
    projectId: 'vi-assistant',
    authDomain: 'vi-assistant.firebaseapp.com',
    storageBucket: 'vi-assistant.firebasestorage.app',
    measurementId: 'G-ZL7K6N355D',
  );
}
